<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageVersion Include="MiniExcel" Version="1.45.0" />
    <PackageVersion Include="MySqlConnector" Version="2.6.2" />
    <PackageVersion Include="Parquet.Net" Version="6.1.0" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>

  <ItemGroup Label="test">
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.14.0" />
    <PackageVersion Include="Testcontainers.MySql" Version="4.14.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
