using ClickHouse.Client.ADO;
using DuckDB.NET.Data;
using Oracle.ManagedDataAccess.Client;
using Testcontainers.ClickHouse;
using WebDataStudio.Server.Drivers.Abstractions;
using WebDataStudio.Server.Drivers.ClickHouse;
using WebDataStudio.Server.Drivers.DuckDb;
using WebDataStudio.Server.Drivers.Oracle;
using WebDataStudio.Server.Models;

namespace WebDataStudio.Server.Tests.Drivers;

/// DuckDB runs in-process: no container, so this suite stays in the fast loop next to SQLite.
public sealed class DuckDbFixture : IDriverFixture
{
    private readonly string _path = Path.Combine(Path.GetTempPath(), $"wds-{Guid.NewGuid():N}.duckdb");

    public IDbDriver Driver { get; } = new DuckDbDriver();
    public ConnectionSpec Spec => new("t", "test", "duckdb", $"Data Source={_path}",
        false, null, null, ConnectionSource.Stored);
    public string? Schema => "main";
    public string? SystemSchema => "information_schema";

    public async ValueTask InitializeAsync()
    {
        await using var db = new DuckDBConnection(Spec.ConnectionString);
        await db.OpenAsync();
        await using var cmd = db.CreateCommand();
        cmd.CommandText = """
            CREATE TABLE people (id INTEGER PRIMARY KEY, name VARCHAR NOT NULL, active BOOLEAN NOT NULL);
            INSERT INTO people VALUES (1,'ada',true),(2,'linus',true),(3,'grace',false);
            CREATE TABLE orders (id INTEGER PRIMARY KEY,
                                 person_id INTEGER NOT NULL REFERENCES people(id),
                                 total DOUBLE);
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    public ValueTask DisposeAsync()
    {
        TestDirectory.RemoveFile(_path);
        return ValueTask.CompletedTask;
    }
}

public class DuckDbContractTests(DuckDbFixture fixture) : DriverContractTests<DuckDbFixture>(fixture);

public sealed class ClickHouseFixture : IDriverFixture
{
    private readonly ClickHouseContainer _container = new ClickHouseBuilder()
        .WithImage("clickhouse/clickhouse-server:24.8-alpine").Build();

    public IDbDriver Driver { get; } = new ClickHouseDriver();
    public ConnectionSpec Spec => new("t", "test", "clickhouse", _container.GetConnectionString(),
        false, null, null, ConnectionSource.Stored);
    public string? Schema => "default";
    public string? SystemSchema => "system";

    public async ValueTask InitializeAsync()
    {
        await _container.StartAsync();
        await using var db = new ClickHouseConnection(Spec.ConnectionString);
        await db.OpenAsync();

        // ClickHouse has no foreign keys; orders keeps the column without a constraint, and the
        // contract suite skips the foreign-key assertion because Caps.ForeignKeys is false.
        foreach (var statement in new[]
        {
            "CREATE TABLE people (id Int32, name String, active UInt8) ENGINE = MergeTree ORDER BY id",
            "INSERT INTO people VALUES (1,'ada',1),(2,'linus',1),(3,'grace',0)",
            "CREATE TABLE orders (id Int32, person_id Int32, total Float64) ENGINE = MergeTree ORDER BY id",
        })
        {
            await using var cmd = db.CreateCommand();
            cmd.CommandText = statement;
            await cmd.ExecuteNonQueryAsync();
        }
    }

    public async ValueTask DisposeAsync() => await _container.DisposeAsync();
}

public class ClickHouseContractTests(ClickHouseFixture fixture) : DriverContractTests<ClickHouseFixture>(fixture);

/// Oracle's container is large and slow to start; the suite is worth it because Oracle is the
/// engine whose syntax differs most from the rest.
public sealed class OracleFixture : IDriverFixture
{
    private readonly Testcontainers.Oracle.OracleContainer _container =
        new Testcontainers.Oracle.OracleBuilder().WithImage("gvenzl/oracle-free:23-slim-faststart").Build();

    public IDbDriver Driver { get; } = new OracleDriver();
    public ConnectionSpec Spec => new("t", "test", "oracle", _container.GetConnectionString(),
        false, null, null, ConnectionSource.Stored);
    public string? Schema => "TEST";
    public string? SystemSchema => "SYS";

    public async ValueTask InitializeAsync()
    {
        await _container.StartAsync();
        await using var db = new OracleConnection(Spec.ConnectionString);
        await db.OpenAsync();

        foreach (var statement in new[]
        {
            "CREATE TABLE people (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "name VARCHAR2(100) NOT NULL, active NUMBER(1) NOT NULL)",
            "INSERT INTO people (name, active) VALUES ('ada', 1)",
            "INSERT INTO people (name, active) VALUES ('linus', 1)",
            "INSERT INTO people (name, active) VALUES ('grace', 0)",
            "CREATE TABLE orders (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "person_id NUMBER NOT NULL REFERENCES people(id), total NUMBER(10,2))",
        })
        {
            await using var cmd = db.CreateCommand();
            cmd.CommandText = statement;
            await cmd.ExecuteNonQueryAsync();
        }
    }

    public async ValueTask DisposeAsync() => await _container.DisposeAsync();
}
